server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://crawling-server.c4y9vm1irfhh.ap-northeast-2.rds.amazonaws.com:3306/test2 #jdbc:mariadb://192.168.201.229:3306/kakao
    username: admin
    password: adminadmin

  #의존성 추가
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    properties:
      hibernate.format_sql: true
    generate-ddl: true

cloud:
  aws:
    credentials:
      accessKey: AKIARIZNV6JYGNGN2CZH # IAM 사용자 엑세스 키
      secretKey: 67CUpdBvEYNRhF4C3zW1pZ7C8GfUuy0DdRE0zn7L # IAM 사용자 비밀 엑세스 키
    s3:
      bucketName: classmoaimage # 버킷명
    region:
      static: ap-northeast-2 # 리전
    stack:
      auto: false # Spring Cloud는 환경 또는 스택을 기반으로 이를 자동으로 감지

logging:
  level:
    web: debug
#  sql.init.mode: always

